### PR TITLE
Use PostCSS 7 & drop support for Node.js 4

### PR DESCRIPTION
**Pull request by realityking**
This aligns the minimum Node.js version with PostCSS 7

### CODE REVIEW

**Comment by RyanZim** [comment]
Looks great; thanks for contributing. I want to get a couple of other dep upgrades merged into the same release, so I'll merge this as soon as I get time to deal with it.

**Comment by realityking** [comment]
Happy to do a follow-up PR bumping all the dev-deps though I'd prefer this one to get merged first to get the new test matrix in.

**Comment by RyanZim** [comment]
There are already greenkeeper PRs for all the deps that I can merge in after this one. I'll try to get it done today or tomorrow.

**Comment by realityking** [comment]
Duhh. Makes sense. Thank you :)

**Comment by realityking** [comment]
Any way I can help, @RyanZim?

**Comment by RyanZim** [comment]
Sorry, I've been crazy busy at work. Today is a software release at work, hopefully I can get to this on the weekend.

**Comment by MaxMilton** [comment]
LGTM :wink:

**Pull request merged**
