### PR TITLE
Support *.pcss extension

### PR DESCRIPTION
**Pull request by meritt**
See https://twitter.com/PostCSS/status/661645290622083073

### CODE REVIEW

**Comment by TrySound** [comment]
:+1:

**Comment by MoOx** [comment]
@meritt just click again and read the whole thread. I think it's a stupid idea and I think we should really not promote that, it's a non-sense. Does babel user use .bjs? I guess no.
Howhever, I am option to add a `extensions` option.

**Comment by meritt** [comment]
@MoOx `extensions` option would be fine for me. You can close PR.

**Comment by MoOx** [comment]
Feel free to make a PR to add `extensions` option.

**Pull request closed without merging**
