### PR TITLE
support sync mode

### LINKED ISSUE #180: Sync mode?
I'm wondering why sync mode was removed in #107?

I'm using `postcss-import` as part of a CSS Modules based stack. If I want to run CSS Modules in a Node or unit test environment (say pre-compiling for ava tests) I need to use [css-modules-require-hook](https://github.com/css-modules/css-modules-require-hook) which is afaiu only able to operate on sync postcss plugins. There's an issue about it here:

https://github.com/css-modules/css-modules-require-hook/issues/58

Async mode by default sounds groovy, but how about re-adding a sync mode in as an option? Or was it removed for specific reasons?

### PR DESCRIPTION
**Pull request by longlho**
fix #180 

We really needed this to work w/ `css-modules-require-hook`

### CODE REVIEW

**Comment by TrySound** [comment]
@longlho It's not required for css-modules. ICSS2 introduces imports support. [This plugin](https://github.com/css-modules/postcss-icss-import) converts syntax

**Comment by longlho** [comment]
@TrySound is there any docs on how that works :-/

**Comment by TrySound** [comment]
Modes introduce large complexity with bad maintainability. Separate project is better solution.

**Comment by TrySound** [comment]
It doesn't work yet. We will release beta of new loader in a few days. Same with css-modulesify and require-hook.

**Comment by TrySound** [comment]
You can help with integration if you want. Just follow icss2 spec
https://medium.com/webpack/the-new-css-workflow-step-1-79583bd107d7

**Pull request closed without merging**
