### PR TITLE
Add resolve tests

### LINKED ISSUE #101: [Feature Request] Import CSS using the package.json main attribute
Hi,

I'm creating pure css packages ([superfly-css](https://github.com/superfly-css)).  The workflow I'm using looks like this:

1) Create new public github repository
2) Clone the repository
3) Run npm init
4) Add the style attribute to package.json
5) Publish to NPM

If postcss-import read the `main` attribute for the css file that the package publishes, it would allow me to skip step 4.  Right now the `main` attribute duplicates the `style` attribute.  

Thoughts?

TIA,
Ole

### PR DESCRIPTION
**Pull request by TrySound**
fix #101

### CODE REVIEW

**Comment by TrySound** [comment]
There is a problem in `resolve` I think. On my windows machine everything is okay.

**Comment by TrySound** [comment]
Done. Sorry for noise. Reverted issue with resolve. Will try to break again in the next time.

**Comment by MoOx** [comment]
Any idea why appveryor is broken?

**Comment by TrySound** [comment]
@MoOx Something wrong with npm. I don't think it make sense. `branch` build was successed. 
P.S. Welcome back :)

**Comment by MoOx** [comment]
So from what I understand, no breaking changes in this PR?

**Comment by TrySound** [comment]
I added `main` field search, made more detailed tests and fixed `options.root` using.

**Comment by MoOx** [comment]
Can you add the added stuff in the CHANGELOG please?

**Pull request merged**
