### PR TITLE
Add `beforeImport` option

### PR DESCRIPTION
**Pull request by finian**
for whitelisting or blacklisting paths  #254

### CODE REVIEW

**Comment by RyanZim** [comment]
Not a bad idea; @ai @MoOx thoughts on this?

**Comment by MoOx** [comment]
Looks overkill to me. If some url should be skipped, it should be built-in.

**Comment by ai** [comment]
Maybe some PostCSS plugin before `postcss-import` is better solution?

**Comment by RyanZim** [comment]
@ai What would the plugin do?

**Comment by ai** [comment]
Find `@import` with blacklisted paths and remove them?

**Comment by RyanZim** [comment]
@ai I'm not sure what the original intent was; I assumed @IonicaBizau wanted to allow the browser to load some paths (instead of inlining them dev-side). Perhaps I'm wrong; @IonicaBizau?

**Comment by IonicaBizau** [comment]
@RyanZim You're right. My idea was that the blacklisted paths would remain as import lines, letting the browser to load them.

**Comment by finian** [comment]
Hi all, thanks for reviewing. My use case: I use webpack to load css (it processes @import things) and use postcss-cssnext to write css. In a css file, I want to import global variables, so I use postcss-cssnext to inline them, but I don't want other @import statements to be inlined (so they can be processed by webpack).

```css
/* variables.css */
:root {
  --mainTextFontSize: 14px;
}


/* module.css */
@import './variables.css'; /* <-- inline this */
@import './module2.css'; /* <-- leave this alone, don't inline it */

.body {
  font-size: var(--mainTextFontSize);
}
```

**Comment by michael-ciniawsky** [comment]
@finian Why should `css-loader` handle the @import instead 😛  ?  
@RyanZim Is `@import http(s)://...` for loading in the browser, not ignored by default atm 👀 ?

**Comment by RyanZim** [comment]
@ai In light of this info, what are your thoughts?

I'm not sure if accepting a function is the right way to go, accepting an array of paths or perhaps a regex would work in most cases.

---

Partially related: I've been thinking for some time about requiring use-cases like this to be implemented as a custom `resolve` function. However, setting up a basic resolver is a bit of work. What if we moved `lib/resolve-id.js` into a separate module so that it could be easily extended?

We could also encourage the creation of "resolver modules," that you could use like: `opts.resolve: require('some-resolver')`; and have a page in the wiki with a list of custom resolver modules that would be useful to other users.

Just an idea.

**Comment by RyanZim** [comment]
@michael-ciniawsky Didn't see your comment while I was writing.

> Why should css-loader handle the @import instead :stuck_out_tongue: ?

Good question!

> Is `@import http(s)://...` for loading in the browser, not ignored by default atm :eyes: ?

`@import "http(s)://..."` & `@import "//url.com"` are ignored currently. If users want to import remote stylesheets, they can use https://github.com/unlight/postcss-import-url.

**Comment by michael-ciniawsky** [comment]
> Good question!

Yep, @webpack we want to try redesign/improve the CSS pipeline where possible, curious of the usecase/why here 😛 

> @import "http(s)://..." & @import "//url.com" are ignored currently. If users want to import remote stylesheets, they can use https://github.com/unlight/postcss-import-url.

Yep, I though so, just uncertain for a moment if I saw it @postcss-partial-import or here a while ago

**Comment by ai** [comment]
@RyanZim not this callback looks better for me :D

**Comment by RyanZim** [comment]
@ai So would you merge this?

I'm still not sure if I like the naming.

**Comment by IonicaBizau** [comment]
@RyanZim I recently opened https://github.com/postcss/postcss/issues/951. It's about resources via paths.

It may be related to this PR. Linking it here just in case.

**Comment by RyanZim** [comment]
@ai Thoughts on this?

**Comment by ai** [comment]
LGTM

**Comment by michael-ciniawsky** [comment]
`options.filter` ? Still not convinced that this is actually needed and is more usecase specific as it seems (`webpack`), while it could be avoided otherwise, but not my call to make 😛

**Comment by RyanZim** [comment]
OK, I guess we can accept this if it's renamed to `options.filter`

**Comment by RyanZim** [comment]
Closed by  #327

**Pull request closed without merging**
