### PR TITLE
Skip comments between imports

### LINKED ISSUE #163: Comments and "@import must precede all other statements"
This CSS:
```css
@import "helpers";


/* ============================================================================
   BASE STYLING
   ============================================================================ */

@import "base/reset";

@import "base/typography";
...
```

Produces this error (for the second ```@import``` statement):
```
@import must precede all other statements (besides @charset)
```

This is kicked because of the comment. This shouldn't be the case though, should it?

### PR DESCRIPTION
**Pull request by TrySound**
fix #163 #162

### CODE REVIEW

**Comment by MoOx** [comment]
:eyes:

**Comment by TrySound** [comment]
My bad. I forget about comments :)

**Comment by MoOx** [comment]
No big deal :)

**Comment by MoOx** [comment]
That's why semver is nice. Just "new" users get some issues, not the entire planet :D

**Comment by TrySound** [comment]
Yeah. That's cool.

**Comment by MoOx** [comment]
https://travis-ci.org/postcss/postcss-import/jobs/105209142

**Comment by MoOx** [comment]
We should use "eslint --fix ." that will autofix most issues before commiting :)

**Pull request merged**
