### PR TITLE
Use PostCSS 6

### PR DESCRIPTION
**Pull request by jonathantneal**
This PR updates PostCSS 6 and all dependencies. It is divided into separate commits, all of which individually pass testing.

- Updates PostCSS 6, which requires changes to .travis.yml and appveyor.yml
- Updates eslint, which requires changes to most test scripts to meet eslint-config-i-am-meticulous requirements
- Updates sugarss, no troubles
- Updates AVA, which requires updates to most tests as the current directory is now the package directory (see avajs/ava#1074)

_Note: eslint did require removing the jspmResolve oddity._

### CODE REVIEW

**Comment by RyanZim** [comment]
eslint-config-i-am-meticulous removed all stylistic rules in favor of prettier; so I'll have to figure out something there. Doesn't need changed for the release, though.
https://github.com/MoOx/eslint-config-i-am-meticulous/blob/master/CHANGELOG.md#600---2017-03-23

**Comment by RyanZim** [comment]
I'll merge this as soon as I have a chance to release

**Comment by nickwaelkens** [comment]
Can't wait to get this one merged 👍

**Comment by RyanZim** [comment]
Hopefully tonight

**Comment by RyanZim** [comment]
@jonathantneal Thanks a lot!

**Pull request merged**
