### PR TITLE
Use async mode only

### PR DESCRIPTION
**Pull request by TrySound**
For now postcss-import isn't async at all. It still uses sync methods. In the next PR I will fix this too.

### CODE REVIEW

**Comment by MoOx** [comment]
This was for legacy purpose (cssnext is still using sync api, I am starting to cleaning things in order to deprecate it, so this won't be a problem soon).
This will need to be released as a breaking change. Can you update README (remove async doc) and prepare CHANGELOG accordingly?
If we you want to continue to iterate this way (nice approach) maybe we should merge in a "dev" branch, then merge in master when releasing? Or do you want to ship this as it flows?

**Comment by TrySound** [comment]
@MoOx Okay let's create dev branch.

**Comment by MoOx** [comment]
I created it from master, can you adjust the scope of the PR?

**Comment by MoOx** [comment]
You could not just update the scope? I didn't find a way to do it myself but I was thinking that's because I didn't create it.

**Comment by TrySound** [comment]
@MoOx No, don't have an idea how to do that.

**Comment by MoOx** [comment]
I tried on some opened PRs I got, it seems it's not doable anymore from github ui...

**Pull request closed without merging**
