### PR TITLE
Add test for nested import ordering

### PR DESCRIPTION
**Pull request by adam-h**
From https://github.com/postcss/postcss-import/issues/168

### CODE REVIEW

**Comment by MoOx** [comment]
@TrySound do you plan to have a look to this (since you introduced the responsibles changes)?

**Comment by TrySound** [comment]
Sure. Will look tomorrow.

**Comment by TrySound** [comment]
I understand the problem. It's all about skipping duplicates. If we want pure duplcations resolving we should do it after building tree. But it's very massive operation. But if current behaviour creates issues should we implement?

**Comment by MoOx** [comment]
Probably

**Comment by adam-h** [comment]
I'd like to advocate for 'yes' to fix this :)

**Comment by TrySound** [comment]
@adam-h Okay. I need some time.

**Comment by jonny-improbable** [comment]
@TrySound is there an update / workaround for this issue?  It's preventing us from upgrading to v8 of postcss-import.

Thanks.

**Comment by jgthms** [comment]
+1

**Comment by adam-h** [comment]
@jonny-improbable I only have a very hacky workaround, which only works for my codebase without modifications. In my case this error results in variables not getting replaced in the resulting CSS. So I created a grunt-exec task to re-build the CSS until there are no variables output.

```coffeescript
    exec:
      css_hack:
        command: ->
          variable_re = /(\$base\-font|\$keyword-highlight|\$emphasis-font)/g
          match = variable_re.exec(grunt.file.read("path/to/output.css"))

          if(match)
            "./node_modules/.bin/grunt css"
          else
            "echo 'OK'"
```

Then made by `build` target run `css` then `exec:css_hack`

**Comment by MoOx** [comment]
@TrySound any clue?

**Comment by TrySound** [comment]
@MoOx Sorry, don't have a time for realization. But I have some ideas. Will try them asap.

**Comment by MoOx** [comment]
@adam-h what do you think about v7 behavior? We might consider reverting to this version if fix is not doable nor easy. New v8 is really weird and seems more complicated to me.

**Comment by MoOx** [comment]
@TrySound are your ideas still around? :D

**Comment by adam-h** [comment]
@MoOx Can't easily try out v7, as my codebase is using the updated `resolve` function at the moment

**Comment by adam-h** [comment]
@TrySound Any update on this?

Found some more edge cases that fail the build randomly that are trickier to workaround. Depending on the timescale I may revert to v7 and rework my build code slightly as @MoOx suggested and see how that works.

**Comment by adam-h** [comment]
@TrySound Did you get anywhere on this? I may have some time in the coming weeks to have a poke at it

**Comment by wc-matteo** [comment]
> In my case this error results in variables not getting replaced in the resulting CSS.
https://github.com/postcss/postcss-import/pull/169#issuecomment-190984734

Same problem here.

Considering that I don't need any new feature introduced in v8, would reverting to v7 be a viable option? Is it fully compatibile with the current version of `postcss`? I checked and this issue doesn't appear there (disabling `skipDuplicates` also solves the issue, but it is less than ideal).

**Comment by MoOx** [comment]
> would reverting to v7

Totally.

In v8, I think there is a change with import scoped by media queries, but nobody use this anyway.

**Btw, if I don't get any update within a month or so, I will revert to v7 implementation _(because I don't have time to maintain/fix v8)_.**

This issue has been open for too long.

**Comment by MoOx** [comment]
FYI https://github.com/postcss/postcss-import/issues/210

**Comment by wc-matteo** [comment]
So this `@import "css/bar.css" (min-width: 25em);` is v8 only?

If so, I don't see any good use cases for it (in my workflow).

**Comment by MoOx** [comment]
It's not v8 only, but I think in some use cases, nested import with mq where failing. @TrySound can say more about this.

**Comment by longlho** [comment]
@MoOx any update on reverting to v7?

**Comment by MoOx** [comment]
Merging to move forward with this mess

**Comment by RyanZim** [comment]
@MoOx See https://github.com/postcss/postcss-import/issues/168#issuecomment-257949358

**Pull request merged**
