### PR TITLE
Add read-cache to load files

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by MoOx** [comment]
Is this closing #47 #48 #74 ?

**Comment by MoOx** [comment]
(You can provide a small description on your PR :p)

**Comment by TrySound** [comment]
I think it solve those issues only partially. read-cache just cache readFile result checking mtime. But it do not cache transformations. Let's leave those issues for the future.

**Comment by MoOx** [comment]
ok. Good start. :)

**Pull request merged**
