### PR TITLE
Added definitions for typescript developers.

### PR DESCRIPTION
**Pull request by OctoD**

### CODE REVIEW

**Comment by RyanZim** [comment]
I am hesitant to support this, since I don't use TypeScript, and can't update the typings.

@ai Opinion on this?

**Comment by ai** [comment]
I accept such PR because outdated definitions is not a big problem

**Comment by ai** [comment]
But in other hand I don't like that we increase node_modules size for all even non-TS users. So it is up to you 😆.

**Comment by RyanZim** [comment]
Sorry, I think I'm going to pass on this. I've accepted TypeScript definitions for another project and it didn't turn out so well. Perhaps submit this to https://github.com/DefinitelyTyped/DefinitelyTyped?

**Pull request closed without merging**
