### PR TITLE
Use async mode only

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by MoOx** [comment]
Nice. Can you now update README and prepare CHANGELOG?
Thanks for your contributions !

**Comment by TrySound** [comment]
Like this?

**Comment by MoOx** [comment]
Good except I will do:
- not add the version (even it's that's going to be that)
- I will use `Removed: async mode/option` as a message with the PR linked like for some others PR.

**Comment by TrySound** [comment]
Squash?

**Comment by MoOx** [comment]
Who cares?

**Comment by MoOx** [comment]
:+1:

**Comment by jedrichards** [comment]
Hey dudes, would be interested for your opinion in https://github.com/postcss/postcss-import/issues/180 :-)

**Pull request merged**
