### PR TITLE
added support for postcss v8

### LINKED ISSUE #427: Compatibility with PostCSS 8
Currently, this plugin is not compatible with [PostCSS 8]. It would be great if you could make this plugin compatible with the latest version.

[PostCSS 8]: https://github.com/postcss/postcss/releases/tag/8.0.0

### PR DESCRIPTION
**Pull request by oscarotero**
Fixes #427
Supersedes #428

I did this changes following the plugin migration guide (https://evilmartians.com/chronicles/postcss-8-plugin-migration). I hope it helps.

### CODE REVIEW

**Comment by oscarotero** [comment]
I'm having the same CI errors than the previous PR. These errors are related with the source-map generation in windows (it seems like is about the directory separation).

**Comment by RyanZim** [comment]
@oscarotero Looks like it's just a paths issue, there's an HTML file in `test/sourcemap` to actually test the sourcemaps in your browser devtools; if the sourcemap is working fine, you can just update the expected result in the tests to get them passing.

**Comment by oscarotero** [comment]
I had to create a different sourcemap for windows to pass the tests, but it's working.

**Comment by RyanZim** [comment]
@oscarotero Were you able to verify that the sourcemap generated on Windows works correctly on Windows? If not, that's fine, just curious.

**Comment by oscarotero** [comment]
@RyanZim No, I don't have any Windows machine to verify that 😅

**Comment by bytestream** [comment]
@RyanZim Anything I can help with to get this merged?

**Review by RyanZim — APPROVED** [review]

**Comment by RyanZim** [comment]
Merged, need to do some other dependency upgrades before I release, but hopefully should be out this week.

**Comment by RyanZim** [comment]
Sorry so long, finally released in v13 yesterday :tada:

**Comment by bytestream** [comment]
Thanks man 🙌

**Pull request merged**
