### PR TITLE
Fixed extension support - clean version

### PR DESCRIPTION
**Pull request by swernerx**
Clean version of previous PR

### CODE REVIEW

**Comment by MoOx** [comment]
What is this fixing? Is this fixing #197 ?
Could you add some tests? Tests help to understand the issue you are fixing :)

**Comment by swernerx** [comment]
I am actually not sure whether it fixes #197... it theory it could.

Generally it would be smart for postcss-import to pass the given selection of extensions to the resolver - this was not done previously.

The second commit is more about mixed environments e.g. where a "classical" imports a sugarss one which imports an .scss file.

I have a project combining these things:
https://github.com/sebastian-software/modern-spa-boilerplate/tree/master/src

I have had some hard time getting understanding the test suite structure... for know I just check whether I do not break existing functionality.

**Comment by MoOx** [comment]
I can't add feature (that you consider as fixes) without any tests (and I don't currently have time to handle those).

**Comment by swernerx** [comment]
Okay, I understand. I am also not sure about the time required. What exactly do you expect from the test? Anything specific to cover.... ? Otherwise I will just try to have the basics done.

**Comment by MoOx** [comment]
Nothing specific, just basic tests please.

**Comment by linxixuan** [comment]
why not merged yet? I need this !

**Comment by izolate** [comment]
@swernerx Please can you add some tests so we can get this PR merged in?

**Comment by RyanZim** [comment]
Superseded by https://github.com/postcss/postcss-import/pull/245. That PR went a slightly different direction, but some ideas were loosely based on this PR, so thanks @swernerx!

**Pull request closed without merging**
