### PR TITLE
Add dependency message support

### LINKED ISSUE #233: Add dependency message
New `postcss-loader` will support `dependency` message to notify webpack about imports. So we need to add few lines on every import:

``` js
result.messages.push({
  type: 'dependency',
  file: absoluteFilePath
})
```

@MoOx @TrySound write me if you need any help with it.

### PR DESCRIPTION
**Pull request by RyanZim**
Resolves #233.

@MoOx @ai Review?

### CODE REVIEW

**Comment by MoOx** [comment]
lgtm but @ai review will make more sense.

**Comment by ai** [comment]
LGTM

**Comment by stephenmathieson** [comment]
I've been wanting this for quite some time =)

**Comment by RyanZim** [comment]
Merged.

Will release this ASAP.

**Comment by RyanZim** [comment]
Released as v8.2.0 :tada:

Go forth and implement!

**Comment by ai** [comment]
Great. Thanks. I will write a tweet about it tomorrow.

**Comment by michael-ciniawsky** [comment]
@RyanZim Nice, great work! :)

**Pull request merged**
