### PR TITLE
Simple entry path detecting

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
opts.from is not documented as I know.

**Comment by MoOx** [comment]
https://github.com/postcss/postcss/blob/master/docs/source-maps.md#postcss-and-source-maps ?

**Comment by TrySound** [comment]
@MoOx I mean it's from option of plugin, not process

**Comment by MoOx** [comment]
Hahaha. Oups.
Maybe we should postcss from option so?

**Comment by TrySound** [comment]
@MoOx source,inout.file is postcss.from

**Comment by MoOx** [comment]
True :)

**Pull request merged**
