### PR TITLE
Fixed bug with hash url

### LINKED ISSUE #29: Bug with Hash URL
Should ignore hash url.

```css
@import url("#");
```

If the processed file with hash url we get an error:

```
/Users/blond/projects/postcss-import/node_modules/postcss-message-helpers/index.js:79
    throw err
          ^
Error: <css input>:15:1: Failed to find '#' from /Users/blond/projects/postcss-import
    in [ 
        /Users/blond/projects/postcss-import/test/fixtures/imports
    ]
    at <css input>:15:1
    at resolveFilename (/Users/blond/projects/postcss-import/index.js:326:11)
    at readAtImport (/Users/blond/projects/postcss-import/index.js:149:26)
    at transformAtImport (/Users/blond/projects/postcss-import/index.js:87:7)
    at Object.tryCatch [as try] (/Users/blond/projects/postcss-import/node_modules/postcss-message-helpers/index.js:53:12)
    at /Users/blond/projects/postcss-import/index.js:86:16
    at Array.forEach (native)
    at parseStyles (/Users/blond/projects/postcss-import/index.js:85:11)
    at /Users/blond/projects/postcss-import/index.js:67:5
    at PostCSS.process (/Users/blond/projects/postcss-import/node_modules/postcss/lib/postcss.js:79:28)
    at compareFixtures (/Users/blond/projects/postcss-import/test/index.js:22:6)

```

### PR DESCRIPTION
**Pull request by andrewblond**
Resolved #29

### CODE REVIEW

**Comment by MoOx** [comment]
Is this valid to import a hash ?!
I understand this is fixing an error but what is the use case?
I am not sure if this should fail silently.

**Comment by andrewblond** [comment]
I ported this behavior from `stylus`: https://github.com/stylus/stylus/blob/master/test/cases/import.include.resolver.absolute.styl#L5.

PR with this change — https://github.com/stylus/stylus/pull/1778.


Perhaps this is a feature `stylus` and this change does not need to port.

**Comment by MoOx** [comment]
The example of the man is on an url().
If you are using url(#), you are in the wrong repo.

I don't see a use case where importing a # should fail silently.

**Comment by andrewblond** [comment]
Thanks!

**Pull request closed without merging**
