### PR TITLE
Suport for alternative PostCSS syntaxes

### PR DESCRIPTION
**Pull request by jonathantneal**
Added: support for alternative PostCSS syntaxes

### CODE REVIEW

**Comment by MoOx** [comment]
I don't understand what this is about. Care to add a test?

**Comment by ai** [comment]
PostCSS 6.0 has custom parsers. So user can work not only with CSS sources, but also with SCSS (for eample, for inline comment). So if it import some file, we need to use parent processor parser.

**Comment by MoOx** [comment]
I see you added postcss-scss as a dev dep but I don't see any tests, did you forget to add them ?

**Comment by tinchoz49** [comment]
:+1: what is the status of this feature? I preffer use postcss-import over to postcss-partial-import but for now i don't have alternative if i'm using SCSS

**Comment by MoOx** [comment]
I am just waiting for a minimal automated test to be able to merge.

**Comment by tinchoz49** [comment]
ahh ok! one more thing. @jonathantneal I think that you need to do some change with the line [367](https://github.com/postcss/postcss-import/blob/master/index.js#L367) because for example for inline comments in SCSS is necessary use postcss-scss as the parser.

maybe something like this, what do you think?
```javascript
var parseFunc = (result.opts && result.opts.parser) 
  ?  result.opts.parser
  :  postcss.parse
var newStyles = parseFunc(fileContent, options)
```

**Comment by jonathantneal** [comment]
Maybe it would be easier if we just merge the two projects, and keep the import functionality like it is in PostCSS import and make the include functionality like it is in PostCSS partial import?

**Comment by MoOx** [comment]
The idea of your plugin is just to add a prefix before the last part of the name of the file right? I don't see how you created another plugin for that and not just did a PR in the first place. This has already been discussed here https://github.com/postcss/postcss-import/issues/39 and the issue is still open (so PR are welcome, has always).

**Comment by CoolGoose** [comment]
+1 on this, any chance of getting this trough ? :) (helps with a lot of projects being sass based)

**Comment by MoOx** [comment]
@CoolGoose If I am correct, I think @TrySound will handle that very soon.

**Comment by MoOx** [comment]
Closed by 9c168b90afee7673df7c617d08a06a076500a499, will land in master soon.

**Pull request closed without merging**
