### PR TITLE
Add media queries tests

### PR DESCRIPTION
**Pull request by TrySound**
New tests works perfectly. This was not possible with old structure. Now we can fix problems fast and furious. :))

### CODE REVIEW

**Comment by TrySound** [comment]
@MoOx  Can you add some impressive message for this change? :)

**Comment by TrySound** [comment]
This was before
https://github.com/postcss/postcss-import/issues/133#issuecomment-168794761

**Comment by TrySound** [comment]
By the way also it process media-queries statement now ;)

**Comment by MoOx** [comment]
Nice work.

**Pull request merged**
