### PR TITLE
Fix onImport "from" option

### LINKED ISSUE #44: onImport has wrong file paths
It looks to me like the first arg of the `onImport` callback is the file that's doing the importing and every subsequent arg is a file that it imports. Is that correct? If so, it's definitely not working properly. I have 3 files:

```css
/* global.css */
@import foo;
```

```css
/* page1.css */
@import foo;
@import bar;
```

```css
/* page2.css */
@import bar;
@import foo;
```

With the following configuration:

```js
require('postcss-import')({
    path: 'styles/blocks',
    onImport: function(files) {
        console.log('========== import ==========');
        files.forEach(function(file) {
            gutil.log('import:', file);
        });
    }
}),
```

And here's what I get in the shell:

```
13:53 $gulp styles
[13:54:12] Using gulpfile z:\gulpfile.js
[13:54:12] Starting 'styles'...
[13:54:12] Finished 'styles' after 37 ms
========== import ===========
[13:54:12] import: z:\styles\sheets\global\global.css
[13:54:12] import: z:\styles\blocks\block-foo.css
========== import ===========
[13:54:12] import: z:\styles\sheets\global\global.css
[13:54:12] import: z:\styles\blocks\block-foo.css
[13:54:12] import: z:\styles\blocks\block-bar.css
========== import ===========
[13:54:12] import: z:\styles\sheets\global\global.css
[13:54:12] import: z:\styles\blocks\block-bar.css
[13:54:12] import: z:\styles\blocks\block-foo.css
```

Notice how global.css is mentioned 3 times here, when it should have mentioned page1.css and page2.css.

Any ideas?

### PR DESCRIPTION
**Pull request by jedmao**
Fixes #44

### CODE REVIEW

**Comment by MoOx** [comment]
This is supposed to fix it already https://github.com/postcss/postcss-import/commit/5e2169d3e75f4fe612579994fdb154d989a71197

**Comment by MoOx** [comment]
Hum maybe I should made the same in the plugin itself.

**Comment by MoOx** [comment]
Any tests to push to confirm the fix ?

**Comment by jedmao** [comment]
@MoOx I can verify that https://github.com/postcss/postcss-import/commit/5e2169d3e75f4fe612579994fdb154d989a71197 does not fix the issue. I currently have version 6.0.0 installed and I'm still getting the following output:

```
13:53 $gulp styles
[13:54:12] Using gulpfile z:\gulpfile.js
[13:54:12] Starting 'styles'...
[13:54:12] Finished 'styles' after 37 ms
========== import ===========
[13:54:12] import: z:\styles\sheets\global\global.css
[13:54:12] import: z:\styles\blocks\block-foo.css
========== import ===========
[13:54:12] import: z:\styles\sheets\global\global.css
[13:54:12] import: z:\styles\blocks\block-foo.css
[13:54:12] import: z:\styles\blocks\block-bar.css
========== import ===========
[13:54:12] import: z:\styles\sheets\global\global.css
[13:54:12] import: z:\styles\blocks\block-bar.css
[13:54:12] import: z:\styles\blocks\block-foo.css
```
The fix in this PR gives me the desired/expected output:
```
13:53 $gulp styles
[13:54:12] Using gulpfile z:\gulpfile.js
[13:54:12] Starting 'styles'...
[13:54:12] Finished 'styles' after 37 ms
========== import ===========
[13:54:12] import: z:\styles\sheets\global\global.css
[13:54:12] import: z:\styles\blocks\block-foo.css
========== import ===========
[13:54:12] import: z:\styles\sheets\page1\page1.css
[13:54:12] import: z:\styles\blocks\block-foo.css
[13:54:12] import: z:\styles\blocks\block-bar.css
========== import ===========
[13:54:12] import: z:\styles\sheets\page2\page2.css
[13:54:12] import: z:\styles\blocks\block-bar.css
[13:54:12] import: z:\styles\blocks\block-foo.css
```
I'll have to investigate further how to write a test for this.

**Comment by MoOx** [comment]
You current PR will break from option for people that specify it by hand, let my try something else.

**Comment by jedmao** [comment]
OK!

**Comment by MoOx** [comment]
Can you try `npm install postcss/postcss-import#fix.options-mutability` ?

**Comment by jedmao** [comment]
That works! Thanks!

**Comment by jedmao** [comment]
I guess you can close this PR along with #44 when you merge `fix.options-mutability`.

**Pull request closed without merging**
