### PR TITLE
v9.0.0 Main PR 

### PR DESCRIPTION
**Pull request by RyanZim**
This is the main PR for v9.0.0.

Merge conflicts will need to be fixed. Does anyone object to me force-pushing to the v9-dev branch?

Attn: @ai @MoOx 
Closes https://github.com/postcss/postcss-import/issues/242

### CODE REVIEW

**Comment by MoOx** [comment]
Just rebase your branch instead of force pushing. It's generally a bad idea if you have to do that.

**Comment by RyanZim** [comment]
Got it! @MoOx

**Comment by RyanZim** [comment]
@ai Can you do the final review of this? I'd like to ship this tomorrow or the day after that (quite busy right now).

**Comment by ai** [comment]
Looks great

**Comment by RyanZim** [comment]
@MoOx Been working crazy overtime on my day job, do you mind shipping v9?

**Comment by RyanZim** [comment]
This is on hold until https://github.com/postcss/postcss-import/issues/253 is decided.

**Comment by RyanZim** [comment]
Will be shipping this tonight. :8ball:

**Comment by ai** [comment]
Don't forget to write a tweet with short overview and link to full changes list. I will RT it.

**Comment by RyanZim** [comment]
@ai I don't have I twitter account, will write overview for you to post, though. Thanks!

**Comment by RyanZim** [comment]
@ai Released, sorry, don't have time to write that post tonight.

**Comment by RyanZim** [comment]
@ai Twitter post:

> postcss-import v9.0.0 is out, featuring better support for custom parsers like SugarSS, and fixing some long-standing issues with webpack.
> 
> See the full list of changes here: https://github.com/postcss/postcss-import/releases/tag/9.0.0

**Comment by ai** [comment]
@RyanZim thanks, tweet was posted :) thanks for great work, such major releases are always huge work.

**Pull request merged**
